
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'dicID ID_LING INDICE LINHA_B VALdic : eses : es LINHA_B ees : ee : INDICE "\\n" itemsitems : items "\\n" itemitems : itemitem : at_concitem : lingat_conc : ID ":" VAL ";"ling : ID_LING ":" VAL at_ts ";"at_ts : at_ts at_tat_ts :at_t : "\\n" "+" ID ":" VAL'
    
_lr_action_items = {'INDICE':([0,5,],[4,4,]),'$end':([1,2,3,7,8,9,10,11,17,20,22,],[0,-1,-3,-2,-4,-6,-7,-8,-5,-9,-10,]),'LINHA_B':([2,3,7,8,9,10,11,17,20,22,],[5,-3,-2,-4,-6,-7,-8,-5,-9,-10,]),'\n':([4,8,9,10,11,17,19,20,21,22,23,28,],[6,14,-6,-7,-8,-5,-12,-9,24,-10,-11,-13,]),'ID':([6,14,25,],[12,12,26,]),'ID_LING':([6,14,],[13,13,]),':':([12,13,26,],[15,16,27,]),'VAL':([15,16,27,],[18,19,28,]),';':([18,19,21,23,28,],[20,-12,22,-11,-13,]),'+':([24,],[25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dic':([0,],[1,]),'es':([0,],[2,]),'e':([0,5,],[3,7,]),'items':([6,],[8,]),'item':([6,14,],[9,17,]),'at_conc':([6,14,],[10,10,]),'ling':([6,14,],[11,11,]),'at_ts':([19,],[21,]),'at_t':([21,],[23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> dic","S'",1,None,None,None),
  ('dic -> es','dic',1,'p_1','med_yacc.py',7),
  ('es -> es LINHA_B e','es',3,'p_2','med_yacc.py',12),
  ('es -> e','es',1,'p_3','med_yacc.py',16),
  ('e -> INDICE \n items','e',3,'p_4','med_yacc.py',20),
  ('items -> items \n item','items',3,'p_5','med_yacc.py',24),
  ('items -> item','items',1,'p_6','med_yacc.py',28),
  ('item -> at_conc','item',1,'p_7','med_yacc.py',32),
  ('item -> ling','item',1,'p_8','med_yacc.py',36),
  ('at_conc -> ID : VAL ;','at_conc',4,'p_9','med_yacc.py',40),
  ('ling -> ID_LING : VAL at_ts ;','ling',5,'p_10','med_yacc.py',44),
  ('at_ts -> at_ts at_t','at_ts',2,'p_11','med_yacc.py',48),
  ('at_ts -> <empty>','at_ts',0,'p_12','med_yacc.py',52),
  ('at_t -> \n + ID : VAL','at_t',5,'p_13','med_yacc.py',56),
]
